import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../core/utils/formatters.dart';
import '../models/analysis_result.dart';
import '../models/verdict.dart';

/// Renders the branded PDF report. Pure function of [AnalysisResult] so the
/// mock report repository can produce it today and an API-backed repository
/// can fetch identical bytes from the server later.
class PdfReportBuilder {
  static Future<Uint8List> build(AnalysisResult result) async {
    final doc = pw.Document();
    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (_) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              'Chai AI',
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.Text(
              'Digital Authenticity Report',
              style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
            ),
            pw.Divider(),
            pw.SizedBox(height: 8),
            _kv('Analyzed file', result.fileName ?? 'Image'),
            _kv('Timestamp', AppFormatters.dateTime(result.timestamp)),
            _kv('Analysis time', AppFormatters.duration(result.analysisDuration)),
            pw.SizedBox(height: 16),
            pw.Container(
              padding: const pw.EdgeInsets.all(14),
              decoration: pw.BoxDecoration(
                color: PdfColor.fromHex(_verdictHex(result.verdict)),
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    result.verdict.label.toUpperCase(),
                    style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.white,
                    ),
                  ),
                  pw.Text(
                    '${(result.confidence * 100).round()}% confidence',
                    style: const pw.TextStyle(
                      fontSize: 12,
                      color: PdfColors.white,
                    ),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 16),
            _section('Explanation'),
            pw.Paragraph(text: result.explanation),
            pw.SizedBox(height: 12),
            _section('Forensic breakdown'),
            ...result.scores.map(
              (s) => pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 4),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(s.category.label),
                    pw.Text(
                      '${(s.value * 100).round()}%',
                      style: pw.TextStyle(
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            pw.SizedBox(height: 12),
            _section('Detected indicators'),
            if (result.indicators.isEmpty)
              pw.Text('No indicators above the confidence threshold.')
            else
              ...result.indicators.map(
                (i) => pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 6),
                  child: pw.Row(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('• '),
                      pw.Expanded(
                        child: pw.Text(
                          '${i.type.label} (${i.severity}, ${(i.confidence * 100).round()}%) — ${i.description}',
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            pw.SizedBox(height: 12),
            _section('Metadata'),
            ...result.metadata.entries.map(
              (e) => pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 3),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(e.key),
                    pw.Text(e.value),
                  ],
                ),
              ),
            ),
            pw.SizedBox(height: 16),
            pw.Divider(),
            pw.SizedBox(height: 6),
            pw.Text(
              'Generated by Chai AI — forensic analysis report.',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
            ),
          ],
        ),
      ),
    );
    return doc.save();
  }

  static pw.Widget _kv(String key, String value) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 4),
        child: pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(key, style: const pw.TextStyle(color: PdfColors.grey600)),
            pw.Text(value, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
          ],
        ),
      );

  static pw.Widget _section(String title) => pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 6),
        child: pw.Text(
          title,
          style: pw.TextStyle(
            fontSize: 13,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.grey900,
          ),
        ),
      );

  static String _verdictHex(Verdict verdict) {
    switch (verdict) {
      case Verdict.original:
        return '0E9F6E';
      case Verdict.aiGenerated:
        return 'DC2626';
    }
  }
}
