name: yukta_authenticity_app
description: "Chai AI — AI-powered Image Authenticity & Forensic Analysis Platform."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  http_parser: ^4.0.2
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  pdf: ^3.10.7
  printing: ^5.12.0
  share_plus: ^7.2.1
  desktop_drop: ^0.4.4
  cross_file: ^0.3.3+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/ChaiAILogo.png
  fonts:
    - family: Footlight MT Light
      fonts:
        - asset: assets/fonts/footlightmtlight.ttf
          weight: 300

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/ChaiAILogo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#0B0C0E"
  image: assets/ChaiAILogo.png
  android: true
  ios: true
