"""Deterministic forensic report builder.

``build_forensic_report`` turns a persisted :class:`Analysis` (with its loaded
child graph) into the typed :class:`ForensicReportDTO`. It is a pure function
over the analysis: no detectors are re-run, no fusion recomputed and no heatmap
regenerated. The same analysis always yields exactly the same report, and every
statement is traceable to the persisted result.
"""

from __future__ import annotations

import re
from collections import OrderedDict

from app.core.enums import Verdict
from app.models.analysis import Analysis, AnalysisContribution, HeatmapRegion
from app.schemas.report import (
    ClassificationComparisonDTO,
    ClassificationSummaryDTO,
    DetectorContributionDTO,
    DetectorExecutionDTO,
    EvidenceItemDTO,
    ForensicReportDTO,
    HeatmapRegionReportDTO,
    HeatmapReportSummaryDTO,
    ImageMetadataReportSummaryDTO,
    ProcessingReportSummaryDTO,
)
from app.services.mappers import format_utc_timestamp, verdict_label

#: The two hypothesis support scores are in (original, ai_generated).
_VERDICT_INDEX = {
    Verdict.ORIGINAL: 0,
    Verdict.AI_GENERATED: 1,
}

#: Version-trail keys stored inside the persisted image-metadata map; the
#: report surfaces them through the processing section instead of as image
#: metadata.
_VERSION_KEYS = frozenset(
    {"framework_version", "pipeline_version", "fusion_version", "detector_versions"}
)

#: Declared-metadata tokens indicating an editing or AI-generation toolchain.
#: They are read verbatim from the image's own metadata; the report never
#: infers provenance beyond what those declarations say.
_SUSPICIOUS_METADATA_TOKENS = (
    "photoshop",
    "gimp",
    "adobe firefly",
    "firefly",
    "midjourney",
    "stable diffusion",
    "dall-e",
    "dalle",
    "comfyui",
    "generated by ai",
    "artificial intelligence",
    "ai-generated",
)

_TOP_EVIDENCE_LIMIT = 8


def _round(value: float, digits: int = 4) -> float:
    """Round a float for stable, readable serialization."""
    return round(value, digits)


def _round_optional(value: float | None, digits: int = 4) -> float | None:
    """Round an optional float (``None`` stays ``None``)."""
    return round(value, digits) if value is not None else None


def _percent(value: float) -> str:
    """Render a ``[0, 1]`` ratio as a whole-number percentage string."""
    return f"{int(round(max(0.0, min(1.0, value)) * 100))}%"


def _ordered_contributions(analysis: Analysis) -> list[AnalysisContribution]:
    """Contributions in persisted rank order (strongest first)."""
    return sorted(analysis.analysis_contributions, key=lambda c: c.position)


def _detector_evidence_map(
    analysis: Analysis,
) -> OrderedDict[str, list[str]]:
    """Recover ``detector -> evidence text`` from the persisted evidence lines.

    The fusion evidence aggregator already prefixes each detector's evidence
    with ``"<detector> — "``, so source attribution is read straight back from
    the stored analysis (no recomputation).
    """
    mapping: OrderedDict[str, list[str]] = OrderedDict()
    for line in sorted(analysis.evidence, key=lambda e: e.position):
        text = line.text.strip()
        if not text:
            continue
        if "—" in text:
            detector, _, body = text.partition("—")
            detector = detector.strip()
            body = body.strip()
            if detector and body:
                mapping.setdefault(detector, []).append(body)
    return mapping


def _build_contributions(
    analysis: Analysis,
) -> tuple[list[DetectorContributionDTO], list[DetectorExecutionDTO]]:
    """Build the per-detector contribution breakdown and processing times."""
    winner = analysis.verdict
    winner_index = _VERDICT_INDEX.get(winner, 0) if winner else 0
    contributions: list[DetectorContributionDTO] = []
    executions: list[DetectorExecutionDTO] = []
    for row in _ordered_contributions(analysis):
        weights = (
            row.hypothesis_original,
            row.hypothesis_generated,
        )
        reasoning = (
            f"measured normalized score {row.normalized_score:.2f}; allocated "
            f"support {weights[0]:.0%} Original, "
            f"{weights[1]:.0%} AI Generated; prefers "
            f"{row.preferred_hypothesis or 'no hypothesis'}."
        )
        contributions.append(
            DetectorContributionDTO(
                detector=row.detector,
                detector_version=row.detector_version,
                normalized_score=_round(row.normalized_score),
                confidence=_round(row.detector_confidence),
                reliability_weight=_round(row.reliability),
                weight_share=_round(row.weight_share),
                contribution=_round(row.contribution),
                contribution_original=_round(weights[0]),
                contribution_ai_generated=_round(weights[1]),
                contribution_winning_class=_round(weights[winner_index]),
                direction=row.direction,
                preferred_hypothesis=row.preferred_hypothesis,
                reasoning=reasoning,
                processing_time_ms=row.processing_time_ms,
            )
        )
        executions.append(
            DetectorExecutionDTO(
                detector=row.detector,
                processing_time_ms=row.processing_time_ms,
            )
        )
    return contributions, executions


def _preferred_weight(contribution: DetectorContributionDTO) -> float:
    """The detector's confidence in the hypothesis it prefers."""
    return max(
        contribution.contribution_original,
        contribution.contribution_ai_generated,
    )


def _rank_evidence(items: list[EvidenceItemDTO]) -> list[EvidenceItemDTO]:
    """Rank evidence deterministically: importance desc, share desc, text asc."""

    def _dedupe(entries: list[EvidenceItemDTO]) -> list[EvidenceItemDTO]:
        seen: set[str] = set()
        unique: list[EvidenceItemDTO] = []
        for item in entries:
            key = item.text.casefold()
            if key in seen:
                continue
            seen.add(key)
            unique.append(item)
        return unique

    items = _dedupe(items)
    return sorted(
        items,
        key=lambda item: (
            -item.importance,
            -(item.contribution or 0.0),
            item.text.casefold(),
        ),
    )


def _build_evidence(
    analysis: Analysis,
    contributions: list[DetectorContributionDTO],
) -> tuple[list[EvidenceItemDTO], list[EvidenceItemDTO]]:
    """Partition the strongest signals into supporting and contradicting.

    Deterministic rules, all traceable to the fused result:

    * A detector whose preferred hypothesis matches the winning class supplies
      supporting evidence; one preferring a different class supplies
      contradicting evidence. The detector's own stored evidence text is used.
    * A detected indicator corroborates a non-original verdict and
      contradicts an Original verdict.
    """
    winner = analysis.verdict
    winner_label = verdict_label(winner) if winner else ""
    evidence_lines = _detector_evidence_map(analysis)

    supporting: list[EvidenceItemDTO] = []
    contradicting: list[EvidenceItemDTO] = []

    for contribution in contributions:
        supports = contribution.preferred_hypothesis == winner_label
        detail = evidence_lines.get(contribution.detector, [])
        text = (
            detail[0]
            if detail
            else (
                f"The {contribution.detector} signal was most consistent with "
                f"{contribution.preferred_hypothesis} "
                f"(normalized score {contribution.normalized_score:.2f})."
            )
        )
        item = EvidenceItemDTO(
            source_detector=contribution.detector,
            text=text,
            importance=_round(
                contribution.contribution_winning_class
                if supports
                else _preferred_weight(contribution)
            ),
            contribution=_round_optional(contribution.contribution),
            severity=None,
            supports_verdict=supports,
        )
        (supporting if supports else contradicting).append(item)

    for indicator in analysis.detected_indicators:
        corroborates = winner is not Verdict.ORIGINAL
        item = EvidenceItemDTO(
            source_detector=None,
            text=indicator.description.strip(),
            importance=_round(indicator.confidence),
            contribution=None,
            severity=indicator.severity.value,
            supports_verdict=corroborates,
        )
        (supporting if corroborates else contradicting).append(item)

    return (
        _rank_evidence(supporting)[:_TOP_EVIDENCE_LIMIT],
        _rank_evidence(contradicting)[:_TOP_EVIDENCE_LIMIT],
    )


def _region_report(region: HeatmapRegion) -> HeatmapRegionReportDTO:
    """Convert a persisted heatmap region into its report representation.

    The stored label is rendered as ``"sources: core (severity)"`` by the
    heatmap generator; the source detector set and severity are recovered from
    that label — never recomputed through image processing.
    """
    label = region.label or ""
    severity: str | None = None
    match = re.match(r"^(.*?)\s*\((\w+)\)$", label)
    if match:
        label = match.group(1).strip()
        severity = match.group(2).strip()
    detectors: list[str] = []
    core = label
    if ":" in label:
        prefix, _, core = label.partition(":")
        detectors = [part.strip() for part in prefix.split("/") if part.strip()]
    return HeatmapRegionReportDTO(
        x=_round(region.x),
        y=_round(region.y),
        width=_round(region.width),
        height=_round(region.height),
        intensity=_round(region.intensity),
        severity=severity,
        label=core.strip() or region.label,
        detectors=detectors,
    )


def _build_heatmap_summary(analysis: Analysis) -> HeatmapReportSummaryDTO:
    """Summarize the persisted heatmap (may be empty for original images)."""
    if analysis.heatmap is None:
        return HeatmapReportSummaryDTO(
            present=False,
            overall_manipulation=0.0,
            region_count=0,
            detector_attribution=[],
            narrative="No manipulation heatmap was recorded for this analysis.",
        )

    regions = [
        _region_report(region)
        for region in sorted(
            analysis.heatmap.regions, key=lambda r: (-r.intensity, r.x, r.y)
        )
    ]
    detectors: list[str] = []
    for region in regions:
        for detector in region.detectors:
            if detector not in detectors:
                detectors.append(detector)
    detectors.sort()

    if regions:
        peak = max(region.intensity for region in regions)
        attribution = f" primarily by {', '.join(detectors)}." if detectors else "."
        narrative = (
            f"{len(regions)} localized suspicious region(s) were detected"
            f"{attribution} The strongest signal peaks at {_percent(peak)}."
        )
    else:
        narrative = "The heatmap recorded no localized suspicious regions."
    return HeatmapReportSummaryDTO(
        present=True,
        overall_manipulation=_round(analysis.heatmap.overall_manipulation),
        region_count=len(regions),
        regions=regions,
        detector_attribution=detectors,
        narrative=narrative,
    )


def _metadata_items(analysis: Analysis) -> OrderedDict[str, str]:
    """The image-metadata map (version trail and secrets excluded).

    Persisted metadata is user-controlled image data; anything that names or
    looks like a secret or a filesystem path is removed before it can reach a
    report.
    """
    return OrderedDict(
        (item.key, item.value)
        for item in sorted(analysis.metadata_items, key=lambda i: i.key)
        if item.key not in _VERSION_KEYS
        and not _is_sensitive_metadata(item.key, item.value)
    )


#: Substrings in a metadata key that mark it as sensitive (api keys, tokens,
#: credentials, connection strings, private configuration).
_SENSITIVE_KEY_TOKENS = (
    "api",
    "apikey",
    "secret",
    "password",
    "passwd",
    "token",
    "auth",
    "credential",
    "jwt",
    "access_key",
    "private_key",
    "database",
    "connection",
    "dsn",
)

#: Value patterns that reveal credentials/keys when present verbatim.
_SENSITIVE_VALUE_PATTERNS = (
    re.compile(r"\bsk-", re.IGNORECASE),
    re.compile(
        r"\b(?:secret|password|token|api[-_]?key|jwt|bearer)\s*=?", re.IGNORECASE
    ),
    re.compile(r"\\(?:users|home|storage|tmp)", re.IGNORECASE),
    re.compile(r"/(?:users|home|storage|tmp)/", re.IGNORECASE),
)


def _is_sensitive_metadata(key: str, value: str) -> bool:
    """Return whether a persisted metadata pair must never reach a report."""
    label = key.casefold()
    if any(token in label for token in _SENSITIVE_KEY_TOKENS):
        return True
    return any(pattern.search(value) for pattern in _SENSITIVE_VALUE_PATTERNS)


def _real(value: str | None) -> str | None:
    """Return the trimmed value unless it is an empty/unknown placeholder."""
    if not value:
        return None
    value = value.strip()
    if value in {"Unknown", "None", "n/a", "-"}:
        return None
    return value


def _build_metadata_summary(analysis: Analysis) -> ImageMetadataReportSummaryDTO:
    """Classify present / absent / suspicious image metadata deterministically."""
    items = _metadata_items(analysis)
    camera = _real(items.get("Camera"))
    software = _real(items.get("Software"))

    exif_keys = {
        "DateTime",
        "DateTimeOriginal",
        "LensModel",
        "Copyright",
        "Make",
        "Model",
    }
    exif_present = camera is not None or any(_real(items.get(key)) for key in exif_keys)

    suspicious_entries: list[str] = []
    for key, value in items.items():
        lowered = value.casefold()
        if any(token in lowered for token in _SUSPICIOUS_METADATA_TOKENS):
            suspicious_entries.append(f"{key}: {value}")

    if suspicious_entries:
        status = "suspicious"
    elif exif_present:
        status = "present"
    else:
        status = "absent"

    if suspicious_entries:
        narrative = (
            "The declared image metadata contains signs of an editing or "
            "AI toolchain: " + "; ".join(suspicious_entries) + "."
        )
    elif exif_present:
        if camera:
            narrative = f"The image declares valid camera metadata ({camera})."
        else:
            narrative = "The image declares EXIF metadata with camera or timing fields."
    else:
        narrative = (
            "No meaningful EXIF metadata was declared for this image; it "
            "carries no camera or software signature."
        )

    return ImageMetadataReportSummaryDTO(
        status=status,
        exif_present=exif_present,
        camera_present=camera is not None,
        software_present=software is not None,
        has_suspicious_entries=bool(suspicious_entries),
        suspicious_entries=suspicious_entries,
        items={key: value for key, value in items.items()},
        narrative=narrative,
    )


def _version_trail(
    analysis: Analysis,
) -> tuple[str, str, str, list[str]]:
    """Return (pipeline, fusion, framework, detector_versions)."""
    items = {item.key: item.value for item in analysis.metadata_items}
    pipeline = items.get("pipeline_version", "")
    fusion = items.get("fusion_version", "")
    framework = items.get("framework_version", "")
    raw_detector = items.get("detector_versions", "")
    detector_versions = (
        [part.strip() for part in raw_detector.split(",") if part.strip()]
        if raw_detector
        else []
    )
    return pipeline, fusion, framework, detector_versions


def _build_processing_summary(
    analysis: Analysis,
    executions: list[DetectorExecutionDTO],
) -> ProcessingReportSummaryDTO:
    """Build the processing summary from the stored analysis."""
    pipeline, fusion, framework, detector_versions = _version_trail(analysis)
    return ProcessingReportSummaryDTO(
        total_analysis_ms=analysis.duration_ms or 0,
        active_detector_count=len(executions),
        detector_execution=executions,
        pipeline_version=pipeline,
        fusion_version=fusion,
        framework_version=framework,
        detector_versions=detector_versions,
    )


def _runner_label(runner_up: Verdict | None) -> str | None:
    """Display label of the runner-up verdict, if any."""
    if runner_up is None:
        return None
    return verdict_label(runner_up)


def _classification_summary(
    analysis: Analysis,
    supporting: list[EvidenceItemDTO],
    contradicting: list[EvidenceItemDTO],
    margin: float | None,
    runner_up: str | None,
) -> ClassificationSummaryDTO:
    """Deterministic, evidence-traceable 'why-this-classification' summary."""
    confidence = max(0.0, min(1.0, analysis.confidence or 0.0))
    summary = (
        f"The image is classified as {verdict_label(analysis.verdict)} with "
        f"{_percent(confidence)} confidence because "
    )
    if supporting:
        top = ", ".join(
            item.source_detector or "image-level evidence" for item in supporting[:3]
        )
        summary += (
            f"{len(supporting)} forensic signal(s) corroborate this outcome, "
            f"including {top}. "
        )
    else:
        summary += (
            "no corroborating forensic signal exceeded the classification thresholds. "
        )
    if contradicting:
        summary += (
            f"However, {len(contradicting)} signal(s) argue against it, "
            f"including {contradicting[0].text}. "
        )
    if margin is not None:
        summary += (
            f"The classification margin over the runner-up "
            f"({runner_up or 'n/a'}) is {_percent(margin)}."
        )
    return ClassificationSummaryDTO(
        verdict=analysis.verdict,
        classification=verdict_label(analysis.verdict),
        confidence=_round(confidence),
        confidence_percent=int(round(confidence * 100)),
        risk=analysis.risk_level,
        margin=_round_optional(margin),
        summary=summary.strip(),
    )


def build_forensic_report(analysis: Analysis) -> ForensicReportDTO:
    """Build the complete, typed forensic report for ``analysis``.

    Raises ``ValueError`` when the analysis has not produced a verdict yet.
    """
    if analysis.verdict is None:
        raise ValueError("An analysis must be completed before a report is built")

    contributions, executions = _build_contributions(analysis)
    supporting, contradicting = _build_evidence(analysis, contributions)

    hypothesis = (
        analysis.hypothesis_original or 0.0,
        analysis.hypothesis_generated or 0.0,
    )
    winner_index = _VERDICT_INDEX.get(analysis.verdict, 0)
    stored_margin = analysis.classification_margin
    if stored_margin is None:
        other_index = 1 - winner_index
        stored_margin = hypothesis[winner_index] - hypothesis[other_index]

    runner_up = _runner_label(analysis.runner_up_verdict)

    comparison = ClassificationComparisonDTO(
        original=_round(hypothesis[0]),
        ai_generated=_round(hypothesis[1]),
        winner=verdict_label(analysis.verdict),
        runner_up=runner_up,
        margin=_round(max(0.0, stored_margin or 0.0)),
        note=(
            "Values are normalized support scores from the deterministic "
            "two-class classifier; they are not calibrated posterior "
            "probabilities."
        ),
    )

    classification = _classification_summary(
        analysis, supporting, contradicting, stored_margin, runner_up
    )

    processing = _build_processing_summary(analysis, executions)
    pipeline = processing.pipeline_version

    return ForensicReportDTO(
        analysis_id=analysis.public_id,
        timestamp=format_utc_timestamp(analysis.created_at),
        pipeline_version=pipeline,
        classification=classification,
        comparison=comparison,
        supporting_evidence=supporting,
        contradicting_evidence=contradicting,
        detector_contributions=contributions,
        heatmap=_build_heatmap_summary(analysis),
        image_metadata=_build_metadata_summary(analysis),
        processing=processing,
    )
